/**
 *  Copyright 2023 Shadowcast
 *  Project Name - Sheepdog-therapeutics
 *  Engineer - Vijayant Jha
 *  Modified By - Vijayant Jha
 */

exports.appConstant = {
  ROUTENOTFOUND: "This route  does not exists",
  OTPNOTMATCHED: "The otp is not matched",
  BADREQUEST: "Bad Request",
  EMAILNOTFOUND: "Email not found",
  INVALIDEMAILORNUMBER:
    "Email or Number you have entered is not processable please try again with diffrent one",
  SUCCESSLOGIN: "Logged in successfully",
  SUCCESSUPDATE: "Successfully updated",
  SUCCESSADDED: "Successfully added",
  SUCCESSDELETED: "Successfully deleted",
  PASSWORDUPDATE: "Password successfully updated",
  UNAUTHORIZED: "Unauthorized",
  WRONGCREDENTIALS: "Wrong Credentials",
  OK: "Ok",
  DELETE: "Successfully deleted",
  USERALREADYEXISTS: "User Already Exists",
  CANNOTCREATEPROFILE: "Can Not create profile",
  CANNOTGETPROFILE: "Cannot get profile",
  CANNOTGETCHANNEL: "Cannot get channel",
  PASSWORDUPDATED: "passowrd updated",
  USEREGISTERED: "User Registered",
  LOGGEDIN: "User LoggedIn",
  ONLYFORPRIMARYUSERS: "Only for primary users",
  CANNOTADDMOREUSERS: "can not add more users",
  SOMETHINGWENTWRONG: "Something went wrong",
  PASSWORDNOTMATCH: "Passwords do not match",
  CANNOTGENERATETOKEN: "cannot generate token",
  TOKENGENERATED: "token generated successfully",
  PROFILECREATED: "profile created successfully",
  NOTIFICATION_NOT_FOUND: "Notification not found",
  NOTIFICATION_FETCHED_SUCCESSFULLY: "Notifications fetched successfully",
  NOTIFICATION_READ_STATUS_CHANGES: "Notification read status changed",
  NO_CONTENT_DISPLAY: "No content to display",
  // admin password
  CANNOT_PERFORM_THIS_ACTION: "no such admin with this email",
  EMAIL_SENT_SUCCESS: "email sent successfully",
  EMAIL_NOT_SENT: "could not sent email",
  // assest ship
  SHIP_CREATED: "ship created successfully",
  SHIP_NOT_CREATED: "could not create ship",
  SHIP_UPDATED: "ship updated successfully",
  SHIP_NOT_UPDATED: "could not update ship",
  SHIP_NOT_FOUND: "could not find ship",
  SHIP_NOT_DELETED: "could not delete ship",
  SHIP_DELETED: "ship deleted successfully",
  SHIP_NOT_PUBLISH:"could not publish ship",
  SHIP_PUBLISH:"ship publish successfully",
  SHIP_UNPUBLISH:"ship unpublish successfully",
  // assest clothing
  CLOTHING_CREATED: "cloth created successfully",
  CLOTHING_NOT_CREATED: "could not create cloth",
  CLOTHING_UPDATED: "cloth updated successfully",
  CLOTHING_NOT_UPDATED: "could not update cloth",
  CLOTH_NOT_FOUND: "could not find cloth",
  CLOTHING_NOT_REMOVED:"could not remove cloth",
  CLOTHING_REMOVED:"cloth removed successfully",
  APARTMENT_CREATED: "apartment created successfully",
  APARTMENT_NOT_CREATED: "could not create apartment",
  APARTMENT_UPDATED: "apartment updated successfully",
  APARTMENT_NOT_UPDATED: "could not update apartment",
  APARTMENT_NOT_FOUND: "could not find apartment",
  APARTMENT_NOT_REMOVED:"could not remove apartment",
  APARTMENT_REMOVED:"apartment removed successfully",
  APARTMENT_NOT_PUBLISH:"could not publish apartment",
  APARTMENT_PUBLISH:"apartment publish successfully",
  APARTMENT_UNPUBLISH:"apartment unpublish successfully",
  THEME_CREATED: "theme created successfully",
  THEME_NOT_CREATED: "could not create theme",
  THEME_NOT_DELETED: "could not delete theme",
  THEME_DELETED: "theme deleted successfully",
  THEME_UPDATED: "theme updated successfully",
  THEME_NOT_UPDATED: "could not update theme",
  THEME_NOT_FOUND: "could not find theme",
  // content takedown
  NO_USER: "no such user exist",
  NO_CONTENT: "no content data found",
  NO_CONTENT_FOUND: "content not found",
  ALREADY_REPORTED: "you've already reported this content",
  SUCCESSFULLY_REPORTED: "your report have been submitted",
  COULD_NOT_CREATE: "could not create",
  CREATED_SUCCESSFUL: "created successfully",
  FETCHED_LIST_FAILED: "couldn't fetched list",
  SUCCESSFUL_FETCHED_LIST: "successfully fetched list",
  // reported user
  NO_USER_AND_REPORT_ID: "cannot report yourself",
  INVALID_REPORT_PARAMS:"invalid params for reporting creator",
  CREATOR_NOT_FOUND:"Creator not found",
  CREATOR_NOT_Active:"Creator not active",
  ADMIN_NOT_FOUND:"Admin not found",
  INVALID_REPORTER_TYPE:"Reporting Entity type is wrong",
  INVALID_CONTENT_TYPE:"Reporting Content type is wrong",
  CREATOR_ALREADY_REPORTED: "you've already reported this creator",
  CONTENT_ALREADY_REPORTED: "you've already reported this content",
  CHANNEL_ALREADY_REPORTED:"you've already reported this channel",
  USER_ALREADY_REPORTED:"you've already reported this user",
  CREATOR_COULD_NOT_REPORTED:"Creator could not reported",
  SUCCESSFULLY_REPORTED_CREATOR: "you have reported creator",
  SUCCESSFULLY_REPORTED_CONTENT: "you have reported content",
  SUCCESSFULLY_REPORTED_CHANNEL:"you have reported channel",
  SUCCESSFULLY_REPORTED_USER:"you have reported user",
  NO_CHANNEL_FOUND:"Channel not found",
  // assest avatar
  AVATAR_CREATED: "avatar created successfully",
  AVATAR_NOT_CREATED: "could not create avatar",
  AVATAR_UPDATED: "avatar updated successfully",
  AVATAR_NOT_UPDATED: "could not update avatar",
  AVATAR_NOT_FOUND: "could not find avatar",
  AVATAR_NOT_DELETED: "could not delete avatar",
  AVATAR_DELETED: "avatar deleted successfully",
  NO_INVENTORY: "Inventory not found",
  AVATAR_PUBLISHED: "avatar published successfully",
  AVATAR_NOT_PUBLISHED: "avatar could not publish",
  PLATFORM_TOKEN_WALLET_TOPUP_FAILED: "Platform token wallet topup failed",
  PLATFORM_TOKEN_WALLET_TOPUP_SUCCEED: "Platform token wallet topup succeed",
  USER_NOT_FOUND: "User not found",
  // Help center
  ACCOUNT_SUPPORT: 0,
  REPORTED_BUGS: 1,
  FEATURE_REQUESTS: 2,
  UNRESOLVED: 0,
  RESOLVED: 1,
  INVALID_TICKET_TYPE: "Invalid ticket type",
  FAILED_TO_FETCH_FEEDBACK: "Failed to fetch feedback",
  FEEDBACK_FETCHED_SUCCESSFULLY: "Feedback fetched successfully",
  NO_DATA_TO_SHOW: "No data to show",
  TICKET_DATA_NOT_FOUND: "Ticket data not found",
  RESPONSE_ADDED_SUCCESSFULLY: "Feedback's response updated successfully",
  FAILED_TO_ADD_RESPONSE: "Failed to add feedback's response",

  // Backup cronjob action-type strings for failed actions
  CASE_EXECUTE_BATCH_TRANSACTIONS: "execute-batch-transaction",

  // Backup cronjob service names
  SERVICE_TOKEN: "token-service"
};
