/**
 *  Copyright 2023 Shadowcast
 *  Project Name - Sheepdog-therapeutics
 *  Engineer - Vijayant Jha
 */

const { appConstant } = require("./constant");

const messageLookupError = {
  100: "Authentication Failed!",
  101: "Admin Already Exists!",
  102: "OTP has expired",
  103: "Invalid OTP!",
  104: "Invalid email!",
  105: "Passwords do not match",
  106: "Wrong Credentials",
  107: "Email does not exists",
  108: "Invalid access token",
  109: "Cannot upload image",
  110: "Cannot delete image",
  111: "Cannot create profile",
  112: "Cannot get profile",
  113: "Current password is incorrect!",
  114: "New Password and Confirm password do not match!",
  115: "No access token found!",
  116: "User is not a creator",
  117: "Cannot create channel",
  118: "Cannot edit channel",
  119: "Cannot get channel",
  120: "Channel Already Exists!",
  121: "Cannot add content",
  122: "Cannot edit content",
  123: "Cannot get content",
  124: "Invalid category",
  125: "Validation Error",
  126: "Cannot delete content",
  127: "Cannot hide content",
  128: appConstant.NOTIFICATION_NOT_FOUND,
  129: "category not available",
  130: "subcategory not available",
  131: "category not created",
  132: "subcategory not created",
  133: "provide mimetype",
  134: "please send a valid mimetype extension",
  135: "file name not saved",
  136: "data not found in database",
  137: "Admin email already registered!",
  138: "Channel Handle already occupied.",
  139: "Creator does not exist",
  151: "Authentication Failed!",
  152: "User Already Exists!",
  153: "OTP has expired",
  154: "Invalid OTP!",
  155: "Invalid email!",
  156: "User not found with this email!",
  157: "Passwords do not match",
  158: "180 videos not found",
  159: "360 videos not found",
  160: "2D videos not found",
  161: "Music videos not found",
  162: "Channel not found",
  163: "UserName already taken",
  164: "Validation failed",
  165: "Failed to accept friend request",
  166: "Failed to reject friend request",
  167: "User not found",
  168: "Notification not found",
  169: "Clothing does not exist",
  170: "Cannot delete Clothing",
  171: "Apartment does not exist",
  172: "Cannot delete Apartment",
  173: appConstant.EMAILNOTFOUND,
  174: appConstant.CANNOT_PERFORM_THIS_ACTION,
  175: appConstant.EMAIL_NOT_SENT,
  176: appConstant.UNAUTHORIZED,
  177: appConstant.APARTMENT_NOT_CREATED,
  178: appConstant.APARTMENT_NOT_FOUND,
  179: appConstant.APARTMENT_NOT_UPDATED,
  180: appConstant.APARTMENT_NOT_DELETED,
  181: appConstant.CLOTHING_NOT_CREATED,
  182: appConstant.CLOTH_NOT_FOUND,
  183: appConstant.CLOTHING_NOT_UPDATED,
  184: appConstant.NO_USER_AND_REPORT_ID,
  185: appConstant.NO_USER,
  186: appConstant.ALREADY_REPORTED,
  187: appConstant.COULD_NOT_CREATE,
  188: appConstant.SHIP_NOT_CREATED,
  189: appConstant.SHIP_NOT_FOUND,
  190: appConstant.SHIP_NOT_UPDATED,
  191: appConstant.SHIP_NOT_DELETED,
  192: appConstant.NO_CONTENT,
  // 193: appConstant.THEME_NOT_CREATED,
  // 194: appConstant.THEME_NOT_FOUND,
  // 195: appConstant.THEME_NOT_DELETED,
  196: appConstant.AVATAR_NOT_CREATED,
  197: appConstant.AVATAR_NOT_FOUND,
  198: appConstant.AVATAR_NOT_UPDATED,
  199: appConstant.AVATAR_NOT_DELETED,
  200: appConstant.AVATAR_NOT_PUBLISHED,
  201: appConstant.APARTMENT_NOT_PUBLISH,
  202: appConstant.SHIP_NOT_PUBLISH,
  203: appConstant.INVALID_REPORT_PARAMS,
  204: appConstant.CREATOR_NOT_FOUND,
  205: appConstant.CREATOR_NOT_Active,
  206: appConstant.ADMIN_NOT_FOUND,
  207: appConstant.INVALID_REPORTER_TYPE,
  208: appConstant.CREATOR_ALREADY_REPORTED,
  209: appConstant.CREATOR_COULD_NOT_REPORTED,
  210: appConstant.NO_CONTENT_FOUND,
  211: appConstant.INVALID_CONTENT_TYPE,
  212: appConstant.CONTENT_ALREADY_REPORTED,
  213: appConstant.NO_CHANNEL_FOUND,
  214: appConstant.CHANNEL_ALREADY_REPORTED,
  215: appConstant.USER_ALREADY_REPORTED,
  216: appConstant.PLATFORM_TOKEN_WALLET_TOPUP_FAILED,
  217: appConstant.INVALID_TICKET_TYPE,
  218: appConstant.FAILED_TO_FETCH_FEEDBACK,
  219: appConstant.TICKET_DATA_NOT_FOUND,
  220: appConstant.FAILED_TO_ADD_RESPONSE,
  221:"Admin not found",
  222:"Invalid token",
  223:"Reset link expired",
  224:"Current password is incorrect",
  225:"Failed to update the password",

};

module.exports = { messageLookupError };
